In [1]:
import sys
import os

print("Python Version:", sys.version)
print("Environment:", os.environ.get("CONDA_DEFAULT_ENV"))
print("Executable Path:", sys.executable)

Python Version: 3.10.19 | packaged by Anaconda, Inc. | (main, Oct 21 2025, 16:41:31) [MSC v.1929 64 bit (AMD64)]
Environment: base
Executable Path: C:\Users\admin\anaconda_files\anaconda3\envs\windows_ocr\python.exe

In [2]:
import numpy as np
import re
import os
import pandas as pd
import asyncio
import ollama
import json
from winrt.windows.media.ocr import OcrEngine
from winrt.windows.graphics.imaging import BitmapDecoder
from winrt.windows.storage import StorageFile
from winrt.windows.globalization import Language

print("GOOD TO GO - WINDOWS OCR READY")

GOOD TO GO - WINDOWS OCR READY

In [3]:
#SETUP EVERYTHING BEFORE WE START WORKING
async def ocr_image_windows(image_path):
    file = await StorageFile.get_file_from_path_async(image_path)
    stream = await file.open_async(1)

    decoder = await BitmapDecoder.create_async(stream)
    software_bitmap = await decoder.get_software_bitmap_async()

    engine = OcrEngine.try_create_from_language(Language("en"))
    result = await engine.recognize_async(software_bitmap)

    return result.text
print("Setup Is Ready")

Setup Is Ready

In [4]:
# 2. IMAGE FOLDER PATH
# ----------------------------
image_folder = r"C:\Users\admin\Desktop\RISHI_WORK12-Aug-2025\current_task_all\open_this\A_JAN_2026_TASKS\pdf\all"

# ----------------------------
# 3. SUPPORTED IMAGE TYPES
# ----------------------------
supported_ext = (".jpg", ".jpeg", ".png") #and you can add more over here

# ----------------------------
# 4. READ & SORT IMAGE FILES
# ----------------------------
all_images = sorted([
    img for img in os.listdir(image_folder)
    if img.lower().endswith(supported_ext)
])

print("GOOD TO GO")

GOOD TO GO

In [5]:
# 5. IMAGE COUNT SUMMARY
# ----------------------------
jpg_count = sum(1 for i in all_images if i.lower().endswith(".jpg"))
jpeg_count = sum(1 for i in all_images if i.lower().endswith(".jpeg"))
png_count = sum(1 for i in all_images if i.lower().endswith(".png"))

total_images = len(all_images)

print(f"Total {total_images} photos found")
print(f"JPG : {jpg_count}")
print(f"JPEG: {jpeg_count}")
print(f"PNG : {png_count}")
print("-" * 40)

Total 89 photos found
JPG : 89
JPEG: 0
PNG : 0
----------------------------------------

# Windows OCR

In [6]:
# ----------------------------
# 6. OCR EACH IMAGE (Windows OCR)
# ----------------------------
records_5 = []

for idx, image_name in enumerate(all_images, start=1):
    card_no = f"card_{idx}"
    image_path = os.path.join(image_folder, image_name)

    print(f"Processing {card_no} -> {image_name}")

    try:
        text = await ocr_image_windows(image_path)
        text = text.strip()
    except Exception as e:
        text = ""
        print(f"❌ Error reading {image_name}: {e}")

    records_5.append({
        "card": card_no,
        "photo_name": image_name,
        "all_text_info": text
    })

print("-" * 40)
print("WINDOWS OCR completed for all images.")

Processing card_1 -> Visiting Card Kannur_page-0001.jpg
Processing card_2 -> Visiting Card Kannur_page-0002.jpg
Processing card_3 -> Visiting Card Kannur_page-0003.jpg
Processing card_4 -> Visiting Card Kannur_page-0004.jpg
Processing card_5 -> Visiting Card Kannur_page-0005.jpg
Processing card_6 -> Visiting Card Kannur_page-0006.jpg
Processing card_7 -> Visiting Card Kannur_page-0007.jpg
Processing card_8 -> Visiting Card Kannur_page-0008.jpg
Processing card_9 -> Visiting Card Kannur_page-0009.jpg
Processing card_10 -> Visiting Card Kannur_page-0010.jpg
Processing card_11 -> Visiting Card Kannur_page-0011.jpg
Processing card_12 -> Visiting Card Kannur_page-0012.jpg
Processing card_13 -> Visiting Card Kannur_page-0013.jpg
Processing card_14 -> Visiting Card Kannur_page-0014.jpg
Processing card_15 -> Visiting Card Kannur_page-0015.jpg
Processing card_16 -> Visiting Card Kannur_page-0016.jpg
Processing card_17 -> Visiting Card Kannur_page-0017.jpg
Processing card_18 -> Visiting Card Kannur_page-0018.jpg
Processing card_19 -> Visiting Card Kasaragode_page-0001.jpg
Processing card_20 -> Visiting Card Kasaragode_page-0002.jpg
Processing card_21 -> Visiting Card Kasaragode_page-0003.jpg
Processing card_22 -> Visiting Card Kasaragode_page-0004.jpg
Processing card_23 -> Visiting Card Kasaragode_page-0005.jpg
Processing card_24 -> Visiting Card Kasaragode_page-0006.jpg
Processing card_25 -> Visiting Card Kasaragode_page-0007.jpg
Processing card_26 -> Visiting Card Malappuram_page-0001.jpg
Processing card_27 -> Visiting Card Malappuram_page-0002.jpg
Processing card_28 -> Visiting Card Malappuram_page-0003.jpg
Processing card_29 -> Visiting Card Malappuram_page-0004.jpg
Processing card_30 -> Visiting Card Malappuram_page-0005.jpg
Processing card_31 -> Visiting Card Malappuram_page-0006.jpg
Processing card_32 -> Visiting Card Malappuram_page-0007.jpg
Processing card_33 -> Visiting Card Malappuram_page-0008.jpg
Processing card_34 -> Visiting Card Malappuram_page-0009.jpg
Processing card_35 -> Visiting Card Malappuram_page-0010.jpg
Processing card_36 -> Visiting Card Malappuram_page-0011.jpg
Processing card_37 -> Visiting Card Malappuram_page-0012.jpg
Processing card_38 -> Visiting Card Malappuram_page-0013.jpg
Processing card_39 -> Visiting Card Plakkad_page-0001.jpg
Processing card_40 -> Visiting Card Plakkad_page-0002.jpg
Processing card_41 -> Visiting Card Plakkad_page-00023.jpg
Processing card_42 -> Visiting Card Plakkad_page-0003-.jpg
Processing card_43 -> Visiting Card Plakkad_page-00031.jpg
Processing card_44 -> Visiting Card Plakkad_page-00033.jpg
Processing card_45 -> Visiting Card Plakkad_page-00036.jpg
Processing card_46 -> Visiting Card Plakkad_page-0004.jpg
Processing card_47 -> Visiting Card Plakkad_page-00043.jpg
Processing card_48 -> Visiting Card Plakkad_page-0005.jpg
Processing card_49 -> Visiting Card Plakkad_page-0008.jpg
Processing card_50 -> Visiting Card Plakkad_page-003.jpg
Processing card_51 -> Visiting Card Trichur_page-0001.jpg
Processing card_52 -> Visiting Card Trichur_page-0002.jpg
Processing card_53 -> Visiting Card Trichur_page-0003.jpg
Processing card_54 -> Visiting card Kochi_page-0001.jpg
Processing card_55 -> Visiting card Kochi_page-0002.jpg
Processing card_56 -> Visiting card Kochi_page-0003.jpg
Processing card_57 -> Visiting card Kochi_page-0004.jpg
Processing card_58 -> Visiting card Kochi_page-0005.jpg
Processing card_59 -> Visiting card Kochi_page-0006.jpg
Processing card_60 -> Visiting card Kochi_page-0007.jpg
Processing card_61 -> Visiting card Kochi_page-0008.jpg
Processing card_62 -> Visiting card Kochi_page-0009.jpg
Processing card_63 -> Visiting card Kochi_page-0010.jpg
Processing card_64 -> Visiting card Kochi_page-0011.jpg
Processing card_65 -> Visiting card Kochi_page-0012.jpg
Processing card_66 -> Visiting card Kochi_page-0013.jpg
Processing card_67 -> Visiting card Kochi_page-0014.jpg
Processing card_68 -> Visiting card Kochi_page-0015.jpg
Processing card_69 -> Visiting card Kochi_page-0016.jpg
Processing card_70 -> Visiting card Kochi_page-0017.jpg
Processing card_71 -> Visiting card Kochi_page-0018.jpg
Processing card_72 -> Visiting card Kochi_page-0019.jpg
Processing card_73 -> Visiting card Trivandrum_page-0001.jpg
Processing card_74 -> Visiting card Trivandrum_page-0002.jpg
Processing card_75 -> Visiting card Trivandrum_page-0003.jpg
Processing card_76 -> Visiting card Trivandrum_page-0004.jpg
Processing card_77 -> Visiting card Trivandrum_page-0005.jpg
Processing card_78 -> Visiting card Trivandrum_page-0006.jpg
Processing card_79 -> Visiting card Trivandrum_page-0007.jpg
Processing card_80 -> Visiting card Trivandrum_page-0008.jpg
Processing card_81 -> Visiting card Trivandrum_page-0009.jpg
Processing card_82 -> Visiting card Trivandrum_page-0010.jpg
Processing card_83 -> Visiting card Trivandrum_page-0011.jpg
Processing card_84 -> Visiting card Trivandrum_page-0012.jpg
Processing card_85 -> Visiting card Trivandrum_page-0013.jpg
Processing card_86 -> Visiting card Trivandrum_page-0014.jpg
Processing card_87 -> Visiting card Trivandrum_page-0015.jpg
Processing card_88 -> Visiting card Trivandrum_page-0016.jpg
Processing card_89 -> Visiting card Trivandrum_page-0017.jpg
----------------------------------------
WINDOWS OCR completed for all images.

In [7]:
# 7. CREATE PANDAS DATAFRAME chose your suitable vairable name
# ----------------------------
business_card = pd.DataFrame(records_5)

In [8]:
#just to make sure ocr worked well or not?
business_card.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 89 entries, 0 to 88
Data columns (total 3 columns):
 #   Column         Non-Null Count  Dtype
---  ------         --------------  -----
 0   card           89 non-null     object
 1   photo_name     89 non-null     object
 2   all_text_info  89 non-null     object
dtypes: object(3)
memory usage: 2.2+ KB

In [9]:
business_card.head(10)

,card,photo_name,all_text_info
0,card_1,Visiting Card Kannur_page-0001.jpg,ALMA THALASSERY
1,card_2,Visiting Card Kannur_page-0002.jpg,ALBERT AUGUSTINE Managing director +91 9961 75...
2,card_3,Visiting Card Kannur_page-0003.jpg,"Fi t Floor, Union Complex South Bazar, Kannur ..."
3,card_4,Visiting Card Kannur_page-0004.jpg,
4,card_5,Visiting Card Kannur_page-0005.jpg,KABE —S T IJC)IC) ARCHITECTURAL I INTERIOR CON...
5,card_6,Visiting Card Kannur_page-0006.jpg,ISHAQUE MOHAMMED M. Tech I Structural Engineer...
6,card_7,Visiting Card Kannur_page-0007.jpg,O -Arc Architectural Interior +91 7907 00? 322...
7,card_8,Visiting Card Kannur_page-0008.jpg,MISTRY SUL DERS SHAH Mötldging bifeetOt 944141...
8,card_9,Visiting Card Kannur_page-0009.jpg,"—DK GROUP— guilders & Designers 7994 sgj 321, ..."
9,card_10,Visiting Card Kannur_page-0010.jpg,LIJU T.V. B.Arch. AllA Architect +91 9048 7218...

 save this all info into excel, if we want to save padnas data frame if we want
--------------------------
file_path = r"C:\Users\admin\Desktop\RISHI_WORK12-Aug-2025\current_task_all\open_this\A_JAN_2026_TASKS\get_text-info_save_in_proper_format\new_data.xlsx"
business_card.to_excel(file_path, index=False)
print("SAVE SCUESSFULLY")

In [10]:
#LET'S BRING GRANITE MODEL TO MAKE SURE IT WORKS
# link to download ollama : https://ollama.com/download/windows
MODEL_NAME = "granite3.2-vision:2b"   # TEXT model (FASTER)
print("Granite text model is ready")

Granite text model is ready

In [11]:
# ----------------------------
# REGEX PATTERNS
# ----------------------------

mobile_pattern = r'(\+?\d[\d\s\-]{8,}\d)'
email_pattern = r'[A-Za-z0-9._%+-]+@[A-Za-z0-9.-]+\.[A-Za-z]{2,}'

def clean_mobile(number):
    digits = re.sub(r'\D', '', number)
    if len(digits) >= 10:
        return digits
    return None

def extract_contact_info(text):
    
    # ---- EMAIL ----
    emails = re.findall(email_pattern, text)
    email = emails[0] if emails else "-"
    
    # ---- MOBILE ----
    raw_numbers = re.findall(mobile_pattern, text)
    
    cleaned_numbers = []
    for num in raw_numbers:
        cleaned = clean_mobile(num)
        if cleaned and cleaned not in cleaned_numbers:
            cleaned_numbers.append(cleaned)
    
    primary = cleaned_numbers[0] if len(cleaned_numbers) > 0 else "-"
    secondary = cleaned_numbers[1] if len(cleaned_numbers) > 1 else "-"
    
    return primary, secondary, email, cleaned_numbers

print("CELL 1: REGEX EXTRACTION READY - THIS TASK IS FINISH PROPERLY")

CELL 1: REGEX EXTRACTION READY - THIS TASK IS FINISH PROPERLY

In [12]:
def remove_contact_info(text, numbers, email):
    
    for num in numbers:
        text = text.replace(num, "")
    
    if email != "-":
        text = text.replace(email, "")
    
    return text.strip()

print("CELL 2: CONTACT REMOVAL READY - THIS TASK IS FINISH PROPERLY")

CELL 2: CONTACT REMOVAL READY - THIS TASK IS FINISH PROPERLY

In [13]:
def extract_from_granite(cleaned_text):
    
    prompt = f"""
You are extracting information from a business card.

STRICT RULES:
1) Do NOT guess.
2) If unsure return "-".
3) Extract only:
   - name (person name only)
   - address (physical location only)
   - additional_info (designation, company, website etc.)

Return ONLY raw JSON in this format:

{{
"name": "",
"address": "",
"additional_info": ""
}}

TEXT:
{cleaned_text}
"""

    try:
        response = ollama.chat(
            model=MODEL_NAME,
            messages=[{"role": "user", "content": prompt}]
        )

        content = response["message"]["content"]
        content = content.replace("```json", "").replace("```", "").strip()

        return json.loads(content)

    except:
        return {
            "name": "-",
            "address": "-",
            "additional_info": "-"
        }

print("CELL 3: GRANITE EXTRACTION READY - THIS TASK IS FINISH PROPERLY")

CELL 3: GRANITE EXTRACTION READY - THIS TASK IS FINISH PROPERLY

In [14]:
final_rows = []

for idx, row in business_card.iterrows():
    
    print(f"Processing {row['card']}")
    
    raw_text = row["all_text_info"]
    
    # STEP 1: REGEX
    primary, secondary, email, numbers = extract_contact_info(raw_text)
    
    # STEP 2: REMOVE CONTACT INFO
    cleaned_text = remove_contact_info(raw_text, numbers, email)
    
    # STEP 3: GRANITE
    structured = extract_from_granite(cleaned_text)
    
    # STEP 4: FINAL COMBINE
    final_rows.append({
        "card": row["card"],
        "photo_name": row["photo_name"],
        "name": structured.get("name", "-"),
        "mobile_no": primary,
        "secondary_mobile_no": secondary,
        "email": email,
        "address": structured.get("address", "-"),
        "additional_info": structured.get("additional_info", "-"),
        "all_text_info": raw_text
    })

print("CELL 4: FINAL STRUCTURING COMPLETED - THIS TASK IS FINISH PROPERLY")

Processing card_1
Processing card_2
Processing card_3
Processing card_4
Processing card_5
Processing card_6
Processing card_7
Processing card_8
Processing card_9
Processing card_10
Processing card_11
Processing card_12
Processing card_13
Processing card_14
Processing card_15
Processing card_16
Processing card_17
Processing card_18
Processing card_19
Processing card_20
Processing card_21
Processing card_22
Processing card_23
Processing card_24
Processing card_25
Processing card_26
Processing card_27
Processing card_28
Processing card_29
Processing card_30
Processing card_31
Processing card_32
Processing card_33
Processing card_34
Processing card_35
Processing card_36
Processing card_37
Processing card_38
Processing card_39
Processing card_40
Processing card_41
Processing card_42
Processing card_43
Processing card_44
Processing card_45
Processing card_46
Processing card_47
Processing card_48
Processing card_49
Processing card_50
Processing card_51
Processing card_52
Processing card_53
Processing card_54
Processing card_55
Processing card_56
Processing card_57
Processing card_58
Processing card_59
Processing card_60
Processing card_61
Processing card_62
Processing card_63
Processing card_64
Processing card_65
Processing card_66
Processing card_67
Processing card_68
Processing card_69
Processing card_70
Processing card_71
Processing card_72
Processing card_73
Processing card_74
Processing card_75
Processing card_76
Processing card_77
Processing card_78
Processing card_79
Processing card_80
Processing card_81
Processing card_82
Processing card_83
Processing card_84
Processing card_85
Processing card_86
Processing card_87
Processing card_88
Processing card_89
CELL 4: FINAL STRUCTURING COMPLETED - THIS TASK IS FINISH PROPERLY

In [15]:
final_info = pd.DataFrame(final_rows)

print(final_info.info())
final_info.head(15)

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 89 entries, 0 to 88
Data columns (total 9 columns):
 #   Column               Non-Null Count  Dtype
---  ------               --------------  -----
 0   card                 89 non-null     object
 1   photo_name           89 non-null     object
 2   name                 89 non-null     object
 3   mobile_no            89 non-null     object
 4   secondary_mobile_no  89 non-null     object
 5   email                89 non-null     object
 6   address              89 non-null     object
 7   additional_info      89 non-null     object
 8   all_text_info        89 non-null     object
dtypes: object(9)
memory usage: 6.4+ KB
None

,card,photo_name,name,mobile_no,secondary_mobile_no,email,address,additional_info,all_text_info
0,card_1,Visiting Card Kannur_page-0001.jpg,ALMA THALASSERY,-,-,-,-,-,ALMA THALASSERY
1,card_2,Visiting Card Kannur_page-0002.jpg,ALBERT AUGUSTINE,919961750309,-,Idesign.albert@gmail.com,"+91 9961 75 03 09 2 nd Floor, Pulikkal Buildin...",OINFOIDESIGNINTERIOR,ALBERT AUGUSTINE Managing director +91 9961 75...
2,card_3,Visiting Card Kannur_page-0003.jpg,Fi t Floor,4972765612,9846050883,anshinteriors@gmail.com,"Union Complex South Bazar, Kannur - 670 00 Kerala",el: 497 2765612 Mob: 98460 50883 Émai!; uww. n...,"Fi t Floor, Union Complex South Bazar, Kannur ..."
3,card_4,Visiting Card Kannur_page-0004.jpg,John Doe,-,-,-,"123 Main St, Anytown, USA",CEO of XYZ Corporation,
4,card_5,Visiting Card Kannur_page-0005.jpg,Er. Sunaij Mohammed K,919895846980,91830408911291,skabestudio@gmail.com,"1st Floor, Jazz Tower, Varam Kannur, Kerala - ...",Civil & Construction +91 9895 846 980 Ar. Shan...,KABE —S T IJC)IC) ARCHITECTURAL I INTERIOR CON...
5,card_6,Visiting Card Kannur_page-0006.jpg,ISHAQUE MOHAMMED M.,919746008877,914972970203,ishaque@arcinsdesign.com,"Indo Oman Complex, Makkani, Kannur","+ 91 9746 00 88 77 Indo Oman Complex, Makkani,...",ISHAQUE MOHAMMED M. Tech I Structural Engineer...
6,card_7,Visiting Card Kannur_page-0007.jpg,O -Arc Architectural Interior,7593009322,-,info@dardinterior.com,"+91 7907 00? 322 +tl 7593 009 322 o Therur, Ka...",www.dafcinterior.cphn,O -Arc Architectural Interior +91 7907 00? 322...
7,card_8,Visiting Card Kannur_page-0008.jpg,MISTRY SUL DERS SHAH,9441416100,04972976100,info@mistrybuilders.com,"Near Sadanand Mermaid Apartment PadatihåPälam,...","For any assistance, call:",MISTRY SUL DERS SHAH Mötldging bifeetOt 944141...
8,card_9,Visiting Card Kannur_page-0009.jpg,DK Group,8089290955,-,-,"7994 sgj 321, 8089 290 955 .Opp„ Javbees COIIe...",DK GROUP Builders & Designers CcinStructjonl I...,"—DK GROUP— guilders & Designers 7994 sgj 321, ..."
9,card_10,Visiting Card Kannur_page-0010.jpg,LIJU T.,919048721847,-,architectslivin@gmail.com,"No. 36, opp. Korjan UP School Thana-Kakkad Roa...",AllA Architect +91 9048 7218 47 www.livinarchi...,LIJU T.V. B.Arch. AllA Architect +91 9048 7218...
10,card_11,Visiting Card Kannur_page-0011.jpg,NIMBLE Majnas k c,919072172073,-,nimbleinterior@gmail.com,"KM Tower. Kakkad Road, South Bazar, Kannur - 02",+91 9072172 073,NIMBLE Majnas k c Managing Partner g +91 90721...
11,card_12,Visiting Card Kannur_page-0012.jpg,K.K MAMMU HAJ' & SONS,9895247672,-,mammusgroup@gmail.com,"9895 247 672, 9387 711 e Chungam, Pappinisseri...",Managing Director,group ARCHITECTURAL & ENGINEERING CONSULTANTS ...
12,card_13,Visiting Card Kannur_page-0013.jpg,Wajed Rehman,919567923892,96871194660,info@rawdesignstudio.in,"9 1st Floor, Fine Complex Saidarpalli, Thalass...","Principal Architect, Raw Design Studio Archite...",I a vv. DESIGN STUDIO Architecture I Interior ...
13,card_14,Visiting Card Kannur_page-0014.jpg,K V GROUP INFRASTRUCTURE DEVELOPERS,919745765765,917034666765,kvgroup.infra@gmail.com,+9197 457 657 65 +91 70 346 667 65 +9190 489 4...,kvgroupinfra,K V GROUP INFRASTRUCTURE DEVELOPERS K V GROUP ...
14,card_15,Visiting Card Kannur_page-0015.jpg,Shebin Mathew,916282126280,-,shebin@sm-architects.in,"3rd Floor, Dream Mall, Chiravakku - Taliparamb...",Principal Architect Mobile: +91 628 212 6280 E...,"SHEBIN MATHEW A ARCHITECTS 3rd Floor, Dream Ma..."

In [16]:
#this will create img link column in excel where we can click on the link and get the img open in our local path
# Construct the hyperlink formula for each row
final_info.insert(
    loc=2,  # position after 'photo_name' (which is index 1)
    column="IMG_Link",
    value=final_info["photo_name"].apply(
        lambda x: f'=HYPERLINK("file:///{image_folder}\\{x}", "Click Here")'
    )
)
print("IMG Link Column Created")

IMG Link Column Created

In [17]:
#just to check the column is create
final_info.info()
final_info.head(5)

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 89 entries, 0 to 88
Data columns (total 10 columns):
 #   Column               Non-Null Count  Dtype
---  ------               --------------  -----
 0   card                 89 non-null     object
 1   photo_name           89 non-null     object
 2   IMG_Link             89 non-null     object
 3   name                 89 non-null     object
 4   mobile_no            89 non-null     object
 5   secondary_mobile_no  89 non-null     object
 6   email                89 non-null     object
 7   address              89 non-null     object
 8   additional_info      89 non-null     object
 9   all_text_info        89 non-null     object
dtypes: object(10)
memory usage: 7.1+ KB

,card,photo_name,IMG_Link,name,mobile_no,secondary_mobile_no,email,address,additional_info,all_text_info
0,card_1,Visiting Card Kannur_page-0001.jpg,"=HYPERLINK(""file:///C:\Users\admin\Desktop\RIS...",ALMA THALASSERY,-,-,-,-,-,ALMA THALASSERY
1,card_2,Visiting Card Kannur_page-0002.jpg,"=HYPERLINK(""file:///C:\Users\admin\Desktop\RIS...",ALBERT AUGUSTINE,919961750309,-,Idesign.albert@gmail.com,"+91 9961 75 03 09 2 nd Floor, Pulikkal Buildin...",OINFOIDESIGNINTERIOR,ALBERT AUGUSTINE Managing director +91 9961 75...
2,card_3,Visiting Card Kannur_page-0003.jpg,"=HYPERLINK(""file:///C:\Users\admin\Desktop\RIS...",Fi t Floor,4972765612,9846050883,anshinteriors@gmail.com,"Union Complex South Bazar, Kannur - 670 00 Kerala",el: 497 2765612 Mob: 98460 50883 Émai!; uww. n...,"Fi t Floor, Union Complex South Bazar, Kannur ..."
3,card_4,Visiting Card Kannur_page-0004.jpg,"=HYPERLINK(""file:///C:\Users\admin\Desktop\RIS...",John Doe,-,-,-,"123 Main St, Anytown, USA",CEO of XYZ Corporation,
4,card_5,Visiting Card Kannur_page-0005.jpg,"=HYPERLINK(""file:///C:\Users\admin\Desktop\RIS...",Er. Sunaij Mohammed K,919895846980,91830408911291,skabestudio@gmail.com,"1st Floor, Jazz Tower, Varam Kannur, Kerala - ...",Civil & Construction +91 9895 846 980 Ar. Shan...,KABE —S T IJC)IC) ARCHITECTURAL I INTERIOR CON...

In [18]:
# save the final info here in this excel file
OUTPUT_FINAL_EXCEL = r"C:\Users\admin\Desktop\RISHI_WORK12-Aug-2025\current_task_all\open_this\A_JAN_2026_TASKS\pdf\pdf_to_excel.xlsx"

final_info.to_excel(OUTPUT_FINAL_EXCEL, index=False)

print("Structured File Saved:", OUTPUT_FINAL_EXCEL)

Structured File Saved: C:\Users\admin\Desktop\RISHI_WORK12-Aug-2025\current_task_all\open_this\A_JAN_2026_TASKS\pdf\pdf_to_excel.xlsx